// src/pages/ImageAI.jsx
import { useState } from "react";

function ImageAI() {
  const [prompt, setPrompt] = useState("");
  const [imageUrl, setImageUrl] = useState("");

  const handleGenerateImage = async () => {
    const response = await fetch("/api/dalle", {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
      },
      body: JSON.stringify({ prompt }),
    });

    const data = await response.json();
    setImageUrl(data.imageUrl);
    setPrompt("");
  };

  return (
    <div className="image-ai-container">
      <h1 className="text-3xl font-bold mb-4">Generate Images with SkelenAI</h1>
      <input
        value={prompt}
        onChange={(e) => setPrompt(e.target.value)}
        placeholder="Describe the image you want..."
        className="input-box"
      />
      <button onClick={handleGenerateImage} className="generate-button">Generate</button>
      {imageUrl && <img src={imageUrl} alt="Generated by AI" className="generated-image" />}
    </div>
  );
}

export default ImageAI;
